class Country {

  const Country({
    required this.name
  });

  final String name;

  @override
  String toString() {
    return '$name()';
  }
}

const List<Country> countryOptions = <Country>[
  Country(name: 'Algeria'),
  Country(name: 'Angola'),
  Country(name: 'Benin'),
  Country(name: 'Botswana'),
  Country(name: 'Burkina Faso'),
  Country(name: 'Burundi'),
  Country(name: 'Cabo Verde'),
  Country(name: 'Cameroon'),
  Country(name: 'Central African Republic'),
  Country(name: 'Chad'),
  Country(name: 'Comoros'),
  Country(name: 'Congo (Brazzaville)'),
  Country(name: 'Congo (Kinshasa)'),
  Country(name: 'Cote d\'Ivoire\''),
  Country(name: 'Djibouti'),
  Country(name: 'Egypt'),
  Country(name: 'Equatorial Guinea'),
  Country(name: 'Eritrea'),
  Country(name: 'Eswatini (formerly Swaziland)'),
  Country(name: 'Ethiopia'),
  Country(name: 'Gabon'),
  Country(name: 'Gambia'),
  Country(name: 'Ghana'),
  Country(name: 'Guinea'),
  Country(name: 'Guinea-Bissau'),
  Country(name: 'Kenya'),
  Country(name: 'Lesotho'),
  Country(name: 'Liberia'),
  Country(name: 'Libya'),
  Country(name: 'Madagascar'),
  Country(name: 'Malawi'),
  Country(name: 'Mali'),
  Country(name: 'Mauritania'),
  Country(name: 'Mauritius'),
  Country(name: 'Morocco'),
  Country(name: 'Mozambique'),
  Country(name: 'Namibia'),
  Country(name: 'Niger'),
  Country(name: 'Nigeria'),
  Country(name: 'Rwanda'),
  Country(name: 'Sao Tome and Principe'),
  Country(name: 'Senegal'),
  Country(name: 'Seychelles'),
  Country(name: 'Sierra Leone'),
  Country(name: 'Somalia'),
  Country(name: 'South Africa'),
  Country(name: 'South Sudan'),
  Country(name: 'Sudan'),
  Country(name: 'Tanzania'),
  Country(name: 'Togo'),
  Country(name: 'Tunisia'),
  Country(name: 'Uganda'),
  Country(name: 'Zambia'),
  Country(name: 'Zimbabwe'),
  Country(name: 'Afghanistan'),
  Country(name: 'Armenia'),
  Country(name: 'Azerbaijan'),
  Country(name: 'Bahrain'),
  Country(name: 'Bangladesh'),
  Country(name: 'Bhutan'),
  Country(name: 'Brunei'),
  Country(name: 'Cambodia'),
  Country(name: 'China'),
  Country(name: 'Cyprus'),
  Country(name: 'Georgia'),
  Country(name: 'India'),
  Country(name: 'Indonesia'),
  Country(name: 'Iran'),
  Country(name: 'Iraq'),
  Country(name: 'Israel'),
  Country(name: 'Japan'),
  Country(name: 'Jordan'),
  Country(name: 'Kazakhstan'),
  Country(name: 'North Korea'),
  Country(name: 'South Korea'),
  Country(name: 'Kuwait'),
  Country(name: 'Kyrgyzstan'),
  Country(name: 'Laos'),
  Country(name: 'Lebanon'),
  Country(name: 'Malaysia'),
  Country(name: 'Maldives'),
  Country(name: 'Mongolia'),
  Country(name: 'Myanmar (Burma)'),
  Country(name: 'Nepal'),
  Country(name: 'Oman'),
  Country(name: 'Pakistan'),
  Country(name: 'Palestine'),
  Country(name: 'Philippines'),
  Country(name: 'Qatar'),
  Country(name: 'Saudi Arabia'),
  Country(name: 'Singapore'),
  Country(name: 'Sri Lanka'),
  Country(name: 'Syria'),
  Country(name: 'Tajikistan'),
  Country(name: 'Thailand'),
  Country(name: 'Timor-Leste'),
  Country(name: 'Turkey'),
  Country(name: 'Turkmenistan'),
  Country(name: 'United Arab Emirates (UAE)'),
  Country(name: 'Uzbekistan'),
  Country(name: 'Vietnam'),
  Country(name: 'Yemen'),
  Country(name: 'Albania'),
  Country(name: 'Andorra'),
  Country(name: 'Austria'),
  Country(name: 'Belarus'),
  Country(name: 'Belgium'),
  Country(name: 'Bosnia and Herzegovina'),
  Country(name: 'Bulgaria'),
  Country(name: 'Croatia'),
  Country(name: 'Cyprus'),
  Country(name: 'Czech Republic'),
  Country(name: 'Denmark'),
  Country(name: 'Estonia'),
  Country(name: 'Finland'),
  Country(name: 'France'),
  Country(name: 'Germany'),
  Country(name: 'Greece'),
  Country(name: 'Hungary'),
  Country(name: 'Iceland'),
  Country(name: 'Ireland'),
  Country(name: 'Italy'),
  Country(name: 'Kosovo'),
  Country(name: 'Latvia'),
  Country(name: 'Liechtenstein'),
  Country(name: 'Lithuania'),
  Country(name: 'Luxembourg'),
  Country(name: 'Malta'),
  Country(name: 'Moldova'),
  Country(name: 'Monaco'),
  Country(name: 'Montenegro'),
  Country(name: 'Netherlands'),
  Country(name: 'North Macedonia'),
  Country(name: 'Norway'),
  Country(name: 'Poland'),
  Country(name: 'Portugal'),
  Country(name: 'Romania'),
  Country(name: 'Russia'),
  Country(name: 'San Marino'),
  Country(name: 'Serbia'),
  Country(name: 'Slovakia'),
  Country(name: 'Slovenia'),
  Country(name: 'Spain'),
  Country(name: 'Sweden'),
  Country(name: 'Switzerland'),
  Country(name: 'Ukraine'),
  Country(name: 'United Kingdom (UK)'),
  Country(name: 'Mexico'),
  Country(name: 'Canada'),
  Country(name: 'United States of America (USA)'),
  Country(name: 'Australia'),
  Country(name: 'Fiji'),
  Country(name: 'Kiribati'),
  Country(name: 'Marshall Islands'),
  Country(name: 'Micronesia'),
  Country(name: 'Nauru'),
  Country(name: 'New Zealand'),
  Country(name: 'Palau'),
  Country(name: 'Papua New Guinea'),
  Country(name: 'Samoa'),
  Country(name: 'Solomon Islands'),
  Country(name: 'Tonga'),
  Country(name: 'Tuvalu'),
  Country(name: 'Vanuatu'),
  Country(name: 'Argentina'),
  Country(name: 'Bolivia'),
  Country(name: 'Brazil'),
  Country(name: 'Chile'),
  Country(name: 'Colombia'),
  Country(name: 'Ecuador'),
  Country(name: 'Guyana'),
  Country(name: 'Paraguay'),
  Country(name: 'Peru'),
  Country(name: 'Suriname'),
  Country(name: 'Uruguay'),
  Country(name: 'Venezuela'),
];